# Generated by Django 3.2.9 on 2021-12-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('codigo', models.IntegerField(default=0)),
                ('dose', models.IntegerField(default=0)),
            ],
        ),
    ]
